#ifndef BOREDOS_OPENTTD_PORT_CONFIG_H
#define BOREDOS_OPENTTD_PORT_CONFIG_H

#define OPENTTD_BOREDOS_WINDOW_WIDTH 640
#define OPENTTD_BOREDOS_WINDOW_HEIGHT 480
#define OPENTTD_BOREDOS_DATA_DIR "/Library/OpenTTD"
#define OPENTTD_BOREDOS_BASESET_DIR "/Library/OpenTTD/baseset"
#define OPENTTD_BOREDOS_REQUIRED_GFX "/Library/OpenTTD/baseset/opengfx-8.0.tar"
#define OPENTTD_BOREDOS_REQUIRED_SFX "/Library/OpenTTD/baseset/opensfx-1.0.3.tar"
#define OPENTTD_BOREDOS_REQUIRED_MSX "/Library/OpenTTD/baseset/openmsx-0.4.2.tar"
#define OPENTTD_BOREDOS_UPSTREAM_COMMIT "a5b1394b9ef28905c2f6e151691ac6bd3948c9a7"

#define OPENTTD_BOREDOS_HAS_NETWORK 0
#define OPENTTD_BOREDOS_HAS_THREADS 0
#define OPENTTD_BOREDOS_HAS_SOUND 0
#define OPENTTD_BOREDOS_HAS_MUSIC 0

#endif
