timeout: 3
verbose: yes

${WALLPAPER_PATH}=boot():/splash.jpg
${INITRD_PATH}=boot():/initrd.tar.lz4

wallpaper: ${WALLPAPER_PATH}
wallpaper_style: stretched
backdrop: 000000
term_margin: 200
interface_branding: BoredOS

/BoredOS
    protocol: limine
    path: boot():/boredos.elf
    module_path: ${INITRD_PATH}
    cmdline: -v init=/bin/yawn.elf

/  └──> BoredOS (Silent)
    protocol: limine
    path: boot():/boredos.elf
    module_path: ${INITRD_PATH}
    cmdline: init=/bin/yawn.elf
